// src/components/buttons/TabButton.vue
<script setup lang="ts">
    import { TAB_LIST_ENTRY_MARGIN } from "../../constants";

    const props = defineProps({
      selected: {
        type: Boolean,
        default: false,
      }
    });
    const emits = defineEmits<{ (e: 'selectTab'): void }>();
    const select = (): void => emits("selectTab");
    const buttonStyle = `margin: ${TAB_LIST_ENTRY_MARGIN};`;
    const buttonClass = props.selected ? 'selected' : '';
</script>

<template>
  <button :style=buttonStyle :class=buttonClass @click=select>
    <slot />
  </button>
</template>

<style>
    button {
        border: 1px solid var(--color-accent);
    }

    .selected {
        background-color: var(--color-accent);
        color: var(--color-bg);
        font-weight: bold;
    }
</style>

// src/components/game/windows/MyApp/TabButton.svelte
<script lang="ts">
    import { createEventDispatcher } from "svelte";
    import { TAB_LIST_ENTRY_MARGIN } from "../../../../scripts/desktopConstants";

    export let index: number;
    export let selected: boolean = false;
    export let data: string;

    let dispatcher = createEventDispatcher();

    const select = (): void => {
        dispatcher("selectTab", { index });
    };
</script>

<button
    style="margin: {TAB_LIST_ENTRY_MARGIN};"
    data-selected={selected}
    on:click={select}
>
    {data}
</button>

<style>
    button {
        border: 1px solid var(--color-accent);
    }

    button[data-selected="true"] {
        background-color: var(--color-accent);
        color: var(--color-bg);
        font-weight: bold;
    }
</style>
