// src/components/ui/ToggleButton.svelte
<script lang="ts">
  export let width: string;
  export let height = "34px";

  export let onClick: (toggled: boolean) => any;
  export let isToggled = false;
  export let activeText: string;
  export let inactiveText: string;
  export let style: string = "";
</script>

<button
  class:toggled={isToggled}
  style="--width: {width};--height: {height};{style}"
  on:click={() => {
    isToggled = !isToggled;
    onClick(isToggled)
  }}
>
  {isToggled ? activeText : inactiveText}
</button>

<style>
  button {
    border: 1px solid var(--color-accent);
    width: var(--width);
    padding: 0;
    height: var(--height);
  }

  .toggled {
    background-color: var(--color-accent);
    color: var(--color-bg);
    font-weight: bold;
  }

  button:hover {
    background-color: var(--color-accent);
    color: var(--color-bg);
    font-weight: bold;
  }
</style>

// src/components/buttons/ToggleButton.vue
<script setup lang="ts">
import { ref } from 'vue';

const props = defineProps({
  width: {
    type: String,
    required: true,
  },
  height: {
    type: String,
    default: "34px",
  },
  isToggled: {
    type: Boolean,
    default: false,
  },
  activeText: {
    type: String,
    required: true,
  },
  inactiveText: {
    type: String,
    required: true,
  },
  style: {
    type: String,
    default: "",
  },
});
const emits = defineEmits<{
  (e: 'click', isToggled: boolean): void;
}>();
const isToggled = ref(props.isToggled);
const buttonClass = ref(props.isToggled ? "toggled" : "");
const style = `--width: ${props.width};--height: ${props.height};${props.style}`;
const onClick = () => {
  isToggled.value = !isToggled.value;
  emits('click', isToggled.value);
}
</script>

<template>
  <button :class=buttonClass :style=style v-on:click=onClick>
    {isToggled ? activeText : inactiveText}
  </button>
</template>

<style scoped>
button {
  border: 1px solid var(--color-accent);
  width: var(--width);
  padding: 0;
  height: var(--height);
}

.toggled {
  background-color: var(--color-accent);
  color: var(--color-bg);
  font-weight: bold;
}

button:hover {
  background-color: var(--color-accent);
  color: var(--color-bg);
  font-weight: bold;
}
</style>
