// src/components/views/SettingsMenu.svelte
<script lang="ts">

  import { appWindow } from "@tauri-apps/api/window";
  import { appState } from "../../stores/appState";
  
  let fullscreen = true;
  let volume = 0.5;
  
  
  // Adjust volume
  $: if (volume >= 0 && volume <= 1) {
    // Adjust volume
    console.log(`Volume: ${volume}`);
  }

  const toggleFullscreen = async () => {
    const newVal = ! await appWindow.isFullscreen();
    appWindow.setFullscreen(newVal);
    fullscreen = newVal;
  };

</script>

<main>

  <h2>Settings</h2>
  
  <label for="fullscreen">Fullscreen</label>
  <input bind:checked={fullscreen} on:change={toggleFullscreen} type="checkbox" name="Fullscreen" id="fullscreen">
  <label for="fullscreen">Volume</label>
  <input bind:value={volume} type="range" name="Volume" min="0" max="1" step="0.01">

  <button on:click={() => appState.set('MainMenu')}>Back</button>
  <button on:click={() => appState.set('Credits')}>Credits</button>

</main>

<style>

</style>

// src/views/SettingsMenu.vue
<script setup lang="ts">
  import { appWindow } from "@tauri-apps/api/window";
  import { AppState, useAppStore } from "../store/app";
  import { ref } from "vue";

  const appStore = useAppStore();
  const volume = ref(0.5);
  const checkBox = ref<HTMLInputElement | null>(null);
  
  const isFullscreen = () => {
    if (checkBox.value) {
      return checkBox.value.checked;
    }
    return false;
  };
  const toggleFullscreen = async () => {
    appWindow.setFullscreen(isFullscreen());
  };
  const gotoMainMenu = () => appStore.setState(AppState.MainMenu);

</script>

<template>
  <main>
    <h2>Settings</h2>
    
    <label for="fullscreen">Fullscreen</label>
    <input v-model="checkBox" @change={toggleFullscreen} type="checkbox" name="Fullscreen" id="fullscreen">
    <label for="fullscreen">Volume</label>
    <input v-bind:value={volume} type="range" name="Volume" min="0" max="1" step="0.01">

    <button @click={gotoMainMenu}>Back</button>
  </main>
</template>
