// src/components/game/windows/Finance/Budgets/Budgets.svelte
<script lang="ts">
    import { invoke } from "@tauri-apps/api/tauri";
    import type { FinanceData } from "../Finance.svelte";
    import ValueCard from "../../templates/ValueCard.svelte";
    import { createEventDispatcher } from "svelte";
    import { handleInvoke } from "../../../../../scripts/util";
    import Welfare from "../../Welfare/Welfare.svelte";

    export let data: FinanceData | undefined;
    const dispatcher = createEventDispatcher();

    enum GameValue {
        TaxRate,
        BusinessTaxRate,
        HealthcareBudget,
        WelfareBudget,
        BusinessBudget,
        SpareBudget,
    }

    const updateGameValue = async (gameValue: GameValue, newValue: any) => {
        if (!data) throw new Error("Data is undefined.");

        switch (gameValue) {
            case GameValue.TaxRate:
                const taxRes = await handleInvoke(
                    dispatcher,
                    invoke("update_tax_rate", { taxRate: newValue }),
                    "finance"
                );

                if (taxRes !== false) {
                    data.tax_rate = newValue;
                    data.expected_person_income = taxRes;
                }

                break;
            case GameValue.BusinessTaxRate:
                const busTaxRes = await handleInvoke(
                    dispatcher,
                    invoke("update_business_tax_rate", { taxRate: newValue }),
                    "finance"
                );

                if (busTaxRes !== false) {
                    data.business_tax_rate = newValue;
                }

                break;
            case GameValue.HealthcareBudget:
                const healthRes = await handleInvoke(
                    dispatcher,
                    invoke("update_healthcare_budget", {
                        newBudget: newValue,
                    }),
                    "finance"
                );

                if (healthRes === false) {
                    break;
                }

                data.healthcare_budget = newValue;
                data.used_hospital_capacity = healthRes.used_hospital_capacity;
                data.total_hospital_capacity =
                    healthRes.total_hospital_capacity;
                break;
            case GameValue.WelfareBudget:
                const welfareRes = await handleInvoke(
                    dispatcher,
                    invoke("update_welfare_budget", {
                        newBudget: newValue,
                    }),
                    "finance"
                );

                if (welfareRes === false) {
                    break;
                }

                data.welfare_budget = newValue;
                break;
            case GameValue.BusinessBudget:
                const busRes = await handleInvoke(
                    dispatcher,
                    invoke("update_business_budget", {
                        newBudget: newValue,
                    }),
                    "finance"
                );

                if (busRes === false) {
                    break;
                }

                data.business_budget = newValue;
                break;
            default:
                break;
        }
    };
</script>

<main>
    {#if data != null}
        <h1>TAXES</h1>

        <ValueCard
            title="Tax Rate"
            appendValueEnd="%"
            currentValue={data.tax_rate}
            data={{
                "Expected Tax Income": `$${data.expected_person_income}`,
            }}
            assignValueFn={(val) =>
                updateGameValue(GameValue.TaxRate, Number(val))}
        />
        <ValueCard
            title="Business Tax"
            appendValueEnd="%"
            currentValue={data.business_tax_rate}
            data={{
                "Expected Business Tax Income": `$${data.expected_business_income}`,
            }}
            assignValueFn={(val) =>
                updateGameValue(GameValue.BusinessTaxRate, Number(val))}
        />

        <h1>BUDGETS</h1>

        <ValueCard
            title="Healthcare"
            appendValueStart="$"
            currentValue={data.healthcare_budget}
            data={{
                Capacity: `${data.used_hospital_capacity}/${
                    data.total_hospital_capacity
                } (${
                    data
                        ? Math.floor(
                              (data.used_hospital_capacity /
                                  data.total_hospital_capacity) *
                                  100
                          )
                        : 0
                }%)`,
                "Spare Capacity": data.spare_hospital_capacity,
            }}
            assignValueFn={(val) =>
                updateGameValue(GameValue.HealthcareBudget, Number(val))}
        />
        <ValueCard
            title="Welfare"
            appendValueStart="$"
            currentValue={data.welfare_budget}
            data={{
                "Used Budget": `$${data.used_welfare_budget}/${
                    data.welfare_budget
                } (${
                    data.welfare_budget != 0
                        ? Math.floor(
                              (data.used_welfare_budget / data.welfare_budget) *
                                  100
                          )
                        : 0
                }%)`,
                "Average Welfare": `${data.average_welfare}%`,
                "Average Unemployed Welfare": `${data.average_welfare_unemployed}%`,
            }}
            assignValueFn={(val) =>
                updateGameValue(GameValue.WelfareBudget, Number(val))}
        />
        <ValueCard
            title="Business"
            appendValueStart="$"
            currentValue={data.business_budget}
            data={{
                "Used Budget": `$${data.used_business_budget}/${
                    data.business_budget
                } (${
                    data.business_budget != 0
                        ? Math.floor(
                              (data.used_business_budget /
                                  data.business_budget) *
                                  100
                          )
                        : 0
                }%)`,
            }}
            assignValueFn={(val) =>
                updateGameValue(GameValue.BusinessBudget, Number(val))}
        />
        <ValueCard
            title="Spare"
            hasAmendButton={false}
            appendValueStart="$"
            currentValue={data.spare_budget}
            data={{}}
            assignValueFn={(val) =>
                updateGameValue(GameValue.SpareBudget, Number(val))}
        />
    {/if}
</main>

<style>
    main {
        width: 100%;
        height: 100%;
        overflow-y: scroll;
    }

    main::-webkit-scrollbar {
        display: none;
    }

    h1 {
        font-size: 25px;
        font-weight: bold;
        margin: 20px 0;
    }
</style>

// src/windows/Finances/Budgets.vue
<script setup lang="ts">
import { handleInvoke } from "src/util/events";
import { useFinanceStore } from "src/store/graphs";
import { ref } from "vue";
import ValueCard from "../../components/cards/ValueCard.vue";

type HealthRes = {
    used_hospital_capacity: number;
    total_hospital_capacity: number;
};

enum GameValue {
    TaxRate,
    BusinessTaxRate,
    HealthcareBudget,
    WelfareBudget,
    BusinessBudget,
    SpareBudget,
}

const graphStore = useFinanceStore();
const data = ref<FinanceData>(graphStore.$state.data);
const app = "finance";
graphStore.$subscribe((_, d) => (data.value = d.data));

// NOTE(dylhack): side effect
const setData = (cb: (data: FinanceData) => void) => {
    cb(data.value);
    graphStore.setGraphData(data.value);
};

const updateGameValue = async (gameValue: GameValue, newValue: number) => {
    if (gameValue === GameValue.TaxRate) {
        const { value: taxRes, success } = await handleInvoke<number>(
            app,
            "update_tax_rate",
            { taxRate: newValue }
        );

        if (success) {
            setData((data) => {
                data.tax_rate = newValue;
                data.expected_person_income = taxRes;
            });
        }
    } else if (gameValue === GameValue.BusinessTaxRate) {
        const { success } = await handleInvoke(
            app,
            "update_business_tax_rate",
            { taxRate: newValue }
        );

        if (success) {
            setData((data) => (data.business_tax_rate = newValue));
        }
    } else if (gameValue === GameValue.HealthcareBudget) {
        const { value: healthRes, success } = await handleInvoke<HealthRes>(
            app,
            "update_healthcare_budget",
            { newBudget: newValue }
        );

        if (success) {
            setData((data) => {
                data.healthcare_budget = newValue;
                data.used_hospital_capacity = healthRes.used_hospital_capacity;
                data.total_hospital_capacity =
                    healthRes.total_hospital_capacity;
            });
        }
    } else if (gameValue === GameValue.WelfareBudget) {
        const { success } = await handleInvoke(
            app,
            "update_welfare_budget",
            { newBudget: newValue }
        );

        if (success) {
            setData((data) => (data.welfare_budget = newValue));
        }
    } else if (gameValue === GameValue.BusinessBudget) {
        const { success } = await handleInvoke(
            app,
            "update_business_budget",
            { newBudget: newValue }
        );

        if (success) {
            setData((data) => (data.business_budget = newValue));
        }
    }
};
</script>

<template>
    <div v-if="data">
        <h1>TAXES</h1>
        <ValueCard
            title="Tax Rate"
            :value="data.tax_rate"
            @amend="updateGameValue(GameValue.TaxRate, $event.valueOf())"
            :detail="{ 'Expected Tax Income': data.expected_person_income }"
        />
        <ValueCard
            title="Business Tax"
            :value="data.business_tax_rate"
            @amend="
                updateGameValue(GameValue.BusinessTaxRate, $event.valueOf())
            "
            :detail="{
                'Expected Business Tax Income': data.expected_business_income,
            }"
        />
        <h1>BUDGETS</h1>
        <ValueCard
            title="Healthcare"
            :value="data.healthcare_budget"
            @amend="
                updateGameValue(GameValue.HealthcareBudget, $event.valueOf())
            "
            :detail="{
                'Used Capacity': `${data.used_hospital_capacity}/${
                    data.total_hospital_capacity
                } (${
                    data
                        ? Math.floor(
                              (data.used_hospital_capacity /
                                  data.total_hospital_capacity) *
                                  100
                          )
                        : 0
                }%)`,
                'Spare Capacity': data.spare_hospital_capacity,
            }"
        />
        <ValueCard
            title="Welfare"
            :value="data.welfare_budget"
            @amend="updateGameValue(GameValue.WelfareBudget, $event.valueOf())"
            :detail="{
                'Used Budget': `$${data.used_welfare_budget}/${
                    data.welfare_budget
                } (${
                    data.welfare_budget != 0
                        ? Math.floor(
                              (data.used_welfare_budget / data.welfare_budget) *
                                  100
                          )
                        : 0
                }%)`,
                'Average Welfare': `${data.average_welfare}%`,
                'Average Unemployed Welfare': `${data.average_welfare_unemployed}%`,
            }"
        />
        <ValueCard
            title="Business"
            :value="data.business_budget"
            @amend="updateGameValue(GameValue.BusinessBudget, $event.valueOf())"
            :detail="{
                'Used Budget': `$${data.used_business_budget}/${
                    data.business_budget
                } (${
                    data.business_budget != 0
                        ? Math.floor(
                              (data.used_business_budget /
                                  data.business_budget) *
                                  100
                          )
                        : 0
                }%)`,
            }"
        />
        <h1>TAXES</h1>
        <ValueCard
            title="Spare"
            :hasAmendButton="false"
            :value="data.spare_budget"
            :detail="{}"
        />
    </div>
</template>

<style>
main {
    width: 100%;
    height: 100%;
    overflow-y: scroll;
}

main::-webkit-scrollbar {
    display: none;
}

h1 {
    font-size: 25px;
    font-weight: bold;
    margin: 20px 0;
}
</style>
