// src/components/game/windows/Finance/Overview/OverviewData.svelte
<script lang="ts">
    import ToggleButton from "../../../../ui/ToggleButton.svelte";
    import type { DataItem } from "./Overview.svelte";

    export let title: string;
    export let data: string;
    export let dataArray: DataItem[];

    const comp = (a: DataItem, b: DataItem): number => {
        if (a.pinned && !b.pinned) {
            return -1;
        } else if (b.pinned && !a.pinned) {
            return 1;
        }

        return 0;
    }
</script>

<div class="container">
    <div style="display: flex;">
        <div class="btn">
            <ToggleButton onClick={(isToggled) => {
                dataArray.forEach((data, idx) => {
                    if (data.title !== title) return;

                    dataArray[idx].pinned = isToggled;
                })
                
                dataArray = dataArray.sort((a, b) => comp(a, b));
            }} width="100px" height="50px">Pin</ToggleButton>
        </div>

        <h1>{title.toUpperCase()}</h1>
    </div>
    <h3>{data}</h3>
</div>

<style>
    h1 {
        font-size: 18px;
        font-weight: bold;
    }

    h3 {
        text-align: left;
        margin-top: 20px;
        font-size: 30px;
    }

    .btn {
        margin-right: 20px;
    }

    .container {
        margin-left: 20px;
        margin-top: 20px;
        margin-bottom: 50px
    }
</style>

// src/windows/OverviewData.vue
<script setup lang="ts">
import { ref } from "vue";

const props = defineProps({
    title: { type: String, required: true },
    data: { type: String, required: true },
});
</script>

<template>
    <div class="container">
        <div style="display: flex">
            <h1>{{ title.toUpperCase() }}</h1>
        </div>
        <h3>{{ data }}</h3>
    </div>
</template>

<style scoped>
h1 {
    font-size: 18px;
    font-weight: bold;
}
h3 {
    text-align: left;
    margin-top: 20px;
    font-size: 30px;
}
.btn {
    margin-right: 20px;
}
.container {
    margin-left: 20px;
    margin-top: 20px;
    margin-bottom: 50px;
    border: solid 1px var(--color-accent);
    padding: 20px;
}
</style>
