// src/App.vue
<script setup lang="ts">
import {
    Chart as ChartJS,
    Title,
    Tooltip,
    Legend,
    LineElement,
    LinearScale,
    PointElement,
    CategoryScale,
} from "chart.js";
import { ref, onMounted, DefineComponent, ComponentOptionsMixin, ExtractPropTypes } from "vue";
import { AppState, useAppStore } from "./store/app";
import LoadingGameVue from "./views/LoadingGame.vue";
import MainMenu from "./views/MainMenu.vue";
import SinglePlayer from "./views/SinglePlayer.vue";
import SettingsMenu from "./views/SettingsMenu.vue";
import Finances from "./windows/Finances.vue";

ChartJS.register(
    Title,
    Tooltip,
    Legend,
    LineElement,
    LinearScale,
    PointElement,
    CategoryScale
);

// TODO(dylhack): replace with "vue-router" (For some reason it doesn't during runtime.)
type Component = DefineComponent<{}, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, string, {}, Readonly<ExtractPropTypes<{}>>, {}>
const appStore = useAppStore();
const component = ref<Component | null>(null);
const routes = new Map([
    [AppState.LoadGameMenu, LoadingGameVue],
    [AppState.MainMenu, MainMenu],
    [AppState.Singleplayer, SinglePlayer],
    [AppState.SettingsMenu, SettingsMenu],
]);

appStore.$subscribe((_, value) => {
    const { state } = value;
    const route = routes.get(state);
    if (!route) {
        console.error(`Impossible condition - no such app state: ${state}`);
        return;
    }
    component.value = route;
});

onMounted(() => {
    document.addEventListener("contextmenu", (event) => event.preventDefault());
});
</script>

<template>
    <div>
        <component :is="component" />
    </div>
</template>

<style scoped>
main {
    width: 100%;
    height: 100%;
}
</style>

// src/App.svelte
<script lang="ts">
    import MainMenu from "./components/views/MainMenu.svelte";
    import NewGameMenu from "./components/views/NewGameMenu.svelte";
    import LoadGameMenu from "./components/views/LoadGameMenu.svelte";
    import MultiplayerMenu from "./components/views/MultiplayerMenu.svelte";
    import SettingsMenu from "./components/views/SettingsMenu.svelte";
    import Credits from "./components/views/Credits.svelte";
    import type Loading from "./components/game/desktop/Loading.svelte";
    import SingleplayerGame from "./components/views/SingleplayerGame.svelte";
    import MultiplayerGame from "./components/views/MultiplayerGame.svelte";
    import { appState } from "./stores/appState";
    import {
        Chart as ChartJS,
        Title,
        Tooltip,
        Legend,
        LineElement,
        LinearScale,
        PointElement,
        CategoryScale,
    } from "chart.js";

    ChartJS.register(
        Title,
        Tooltip,
        Legend,
        LineElement,
        LinearScale,
        PointElement,
        CategoryScale
    );
    import "chart.js/auto";

    type AnyAppState =
        | typeof MainMenu
        | typeof NewGameMenu
        | typeof LoadGameMenu
        | typeof MultiplayerMenu
        | typeof SettingsMenu
        | typeof Credits
        | typeof Loading
        | typeof SingleplayerGame
        | typeof MultiplayerGame;

    let currentComponent: AnyAppState | null = null;

    appState.subscribe((value) => {
        switch (value) {
            case "MainMenu":
                currentComponent = MainMenu;
                break;

            case "NewGameMenu":
                currentComponent = NewGameMenu;
                break;

            case "LoadGameMenu":
                currentComponent = LoadGameMenu;
                break;

            case "MultiplayerMenu":
                currentComponent = MultiplayerMenu;
                break;

            case "SettingsMenu":
                currentComponent = SettingsMenu;
                break;

            case "Credits":
                currentComponent = Credits;
                break;

            case "Singleplayer":
                currentComponent = SingleplayerGame;
                break;

            case "Multiplayer":
                currentComponent = MultiplayerGame;
                break;

            default:
                currentComponent = null;
                console.error(
                    `Impossible condition - no such app state: ${value}`
                );
                break;
        }
    });

    document.addEventListener("contextmenu", (event) => event.preventDefault());
</script>

<main>
    {#if currentComponent != null}
        <svelte:component this={currentComponent} />
    {:else}
        <p>Undefined app state</p>
    {/if}
</main>

<style>
    main {
        width: 100%;
        height: 100%;
    }
</style>
